In [29]:
import numpy
import pandas

mu_systolic_high, sigma_systolic_high = 140, 5
mu_diastolic_high, sigma_diastolic_high = 90, 5
mu_systolic_low, sigma_systolic_low = 90, 5
mu_diastolic_low, sigma_diastolic_low = 60, 5

In [23]:
systolic_high = numpy.random.normal(mu_systolic_high, sigma_systolic_high, 100)
diastolic_high = numpy.random.normal(mu_diastolic_high, sigma_diastolic_high, 100)
systolic_low = numpy.random.normal(mu_systolic_low, sigma_systolic_low, 100)
diastolic_low = numpy.random.normal(mu_diastolic_low, sigma_diastolic_low, 100)

In [36]:
data = [systolic_high.transpose(), diastolic_high.transpose(), systolic_low.transpose(), diastolic_low.transpose()]

In [31]:
print data

[array([ 139.10910472,  137.4051026 ,  138.74892383,  143.32274661,
        144.4864747 ,  139.56345495,  131.9606164 ,  132.72786191,
        145.70332662,  144.16198495,  148.24502378,  139.63632976,
        135.00114728,  145.47162887,  135.73396939,  146.90552135,
        144.17197814,  135.14700538,  145.3130618 ,  130.51786998,
        148.02223104,  149.26804405,  134.49230918,  146.06258657,
        137.94661868,  137.11169227,  142.13875934,  137.16110613,
        139.79773182,  136.99833343,  145.90320545,  142.04703129,
        132.11154808,  137.43249424,  136.91057755,  134.60617449,
        145.35305419,  133.417124  ,  145.59249326,  137.68673373,
        156.9478422 ,  136.30022411,  138.39277586,  134.20719398,
        135.11971156,  136.90743083,  139.66928155,  139.85277327,
        139.98105069,  144.38359358,  138.49864327,  141.56340025,
        138.52921537,  134.48392394,  133.21729543,  147.56375083,
        150.02047186,  133.0834487 ,  135.53647287,  143.76724986,
        141.24681865,  134.56215196,  139.3003195 ,  138.14918583,
        146.75525489,  133.89855477,  133.32836335,  136.08504768,
        141.28186168,  148.16159934,  133.14132926,  132.65475847,
        135.50744542,  140.26115743,  144.25946783,  133.71713164,
        141.55423715,  140.84505498,  144.98652242,  145.75137115,
        139.8842892 ,  140.31746391,  136.32787146,  144.66814847,
        141.39273193,  140.18552681,  141.01042429,  139.99211102,
        142.29473664,  144.79014287,  138.21196276,  135.62378981,
        141.13801905,  142.73340051,  139.44154698,  139.91445785,
        139.79657545,  145.50750345,  139.12740257,  140.75861742]), array([  89.24541825,   86.00950477,   89.23808968,   90.23468293,
         92.22541995,   90.49225723,   88.19093648,   93.27377101,
         84.92055641,   83.49734641,   92.8995926 ,   89.41495233,
         95.36787949,   83.71347527,  102.23993123,   78.29170257,
         96.93287496,   86.31710706,   91.55000016,   95.35217114,
         90.42172931,   95.73493554,   85.43733075,   98.3183733 ,
         74.392634  ,   92.84044926,   94.40812648,   93.12196979,
         86.21470284,   88.20579151,   94.09253686,   77.22693862,
         87.85182094,   95.28055974,   83.19046874,   87.64314441,
         84.89184195,   94.72010292,   86.58536832,   90.38047124,
         84.06966481,   93.56474211,   84.6383093 ,   85.68668011,
         92.84503543,   88.19680326,   90.25867915,   89.12478063,
         88.14776164,   86.86571334,   90.86831129,  102.5138164 ,
         87.37158812,   87.25702829,   87.5921704 ,   84.82362695,
         91.74463853,   90.73851059,   91.73520288,   80.21616406,
         92.27657219,   86.54084824,   92.04886609,   90.90306184,
         84.63831083,   87.91554159,   84.45796278,   84.80129542,
         91.71700024,   94.62224449,   85.43202198,   88.42753638,
         94.57140717,   92.40865237,   89.29686322,   96.66768094,
         87.14849695,   93.17391572,   90.0351474 ,   88.9629469 ,
         90.3306794 ,   91.23428976,   93.37071207,   93.73449845,
         92.05582668,   91.76608133,   87.14307874,   88.91757895,
         92.57637231,   91.12661104,   94.22954742,   88.50954381,
         90.7803251 ,   89.30262039,   86.49060947,   96.56969934,
         92.58944329,   91.83499554,   88.39010421,   88.09909607]), array([  94.24270364,   85.61868935,   98.8354942 ,   94.62769272,
         86.67810234,   93.30332661,   96.48432035,   88.21852967,
         90.73512107,   91.12210835,   88.69080813,   91.00016764,
         88.45002838,   87.34790758,   91.15888099,   88.27871337,
         88.49468211,   92.74843209,   90.01496033,   90.34674761,
         83.00500068,   90.02912716,   95.41752572,   89.93850228,
         84.41709737,   89.80430273,   95.31273615,   94.55809656,
         99.24850768,   89.3258524 ,   92.54770274,   99.2020677 ,
         91.38654048,   91.85781161,   91.55537827,   90.72431146,
         97.06636899,   74.90251258,   84.91915511,   88.28341241,
         99.46703725,   96.05767581,   85.63896521,   85.44075191,
         85.34605832,   94.4569727 ,   82.10284747,  102.08860661,
         91.63732082,   93.64837012,   91.28991429,   80.18036743,
         95.15581469,   98.61951808,   91.47531197,   89.04269428,
         89.60608924,   81.76059312,   93.94553134,   83.01461095,
         85.71688673,   96.07170732,   79.70279263,   94.71290912,
         83.95211631,   90.13333572,   89.63488158,   92.72291045,
         93.1848644 ,  101.4457588 ,   91.4190127 ,   84.31181145,
         87.68557449,   91.74060369,   98.54686376,   96.96550284,
         91.3001163 ,   93.48776339,   90.13704197,   94.91128013,
         90.43901983,   93.08244588,   80.13069674,   88.68802704,
         93.76324618,   86.17764499,   90.21420131,   92.26798018,
         80.24690611,   93.26796345,   92.42434729,   93.76723153,
         90.31413514,   94.08091027,   83.58654246,   85.98297075,
         95.34655504,   95.71477432,   80.52737379,   86.82838071]), array([ 71.91052794,  49.01025618,  58.19192727,  58.97957352,
        56.62798958,  47.33771079,  55.95522968,  60.69398124,
        59.43303317,  52.80016735,  67.43188093,  55.47364147,
        59.29719337,  65.86727043,  57.09791242,  64.32982826,
        66.26065259,  52.7381828 ,  60.394462  ,  55.29570285,
        57.53463561,  57.38134957,  67.63277772,  67.46238355,
        57.76211462,  55.49894081,  65.30348109,  62.29764274,
        65.17884627,  57.63681856,  63.58334938,  59.84583069,
        57.10818883,  60.50482295,  55.12258844,  57.55812331,
        64.36627878,  58.12795199,  57.01649411,  56.6860336 ,
        63.24206206,  62.67917111,  64.66735621,  55.86766365,
        59.12956682,  54.06471537,  60.04071564,  70.31502881,
        59.46265142,  61.65121484,  60.12658532,  57.18769802,
        49.61807822,  64.06265448,  56.85129299,  57.26476946,
        55.9326614 ,  64.61522205,  64.57344332,  63.10592231,
        56.72764366,  65.11723995,  60.51254541,  50.96665996,
        59.60977703,  49.33724156,  57.19650513,  60.18809468,
        66.62777812,  59.7203332 ,  62.47541256,  55.83523875,
        61.64621538,  66.58634331,  53.357142  ,  62.90555759,
        54.08123435,  62.33710407,  58.84531572,  54.08180713,
        56.76438553,  60.15605329,  64.26942469,  57.96973368,
        66.23340335,  59.64540048,  63.09478991,  60.73214518,
        54.32092758,  58.90244283,  52.15829246,  68.18758876,
        64.60304217,  67.65634247,  63.87521997,  58.84775208,
        60.47450065,  53.55327271,  59.21146971,  59.25856045])]

In [38]:
pandas.DataFrame(data)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,139.109105,137.405103,138.748924,143.322747,144.486475,139.563455,131.960616,132.727862,145.703327,144.161985,...,138.211963,135.623790,141.138019,142.733401,139.441547,139.914458,139.796575,145.507503,139.127403,140.758617
1,89.245418,86.009505,89.238090,90.234683,92.225420,90.492257,88.190936,93.273771,84.920556,83.497346,...,94.229547,88.509544,90.780325,89.302620,86.490609,96.569699,92.589443,91.834996,88.390104,88.099096
2,94.242704,85.618689,98.835494,94.627693,86.678102,93.303327,96.484320,88.218530,90.735121,91.122108,...,92.424347,93.767232,90.314135,94.080910,83.586542,85.982971,95.346555,95.714774,80.527374,86.828381
3,71.910528,49.010256,58.191927,58.979574,56.627990,47.337711,55.955230,60.693981,59.433033,52.800167,...,52.158292,68.187589,64.603042,67.656342,63.875220,58.847752,60.474501,53.553273,59.211470,59.258560